# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

quiz = Quiz.create(name: "Dev Bootcamp Quiz")
question = quiz.questions.create(question: "Who is your favorite teacher?")
choiceA = question.choices.create(choice: "Matt", is_correct: false)
choiceB = question.choices.create(choice: "Strand", is_correct: false)
choiceC = question.choices.create(choice: "Jeffrey", is_correct: false)
choiceD = question.choices.create(choice: "None of the Above", is_correct: true)
question = quiz.questions.create(question: "What is the color blue")
choiceA = question.choices.create(choice: "Blue", is_correct: false)
choiceB = question.choices.create(choice: "Black", is_correct: false)
choiceC = question.choices.create(choice: "Round", is_correct: false)
choiceD = question.choices.create(choice: "None of the Above", is_correct: true)
question = quiz.questions.create(question: "Is the bathroom empty?")
choiceA = question.choices.create(choice: "No", is_correct: false)
choiceB = question.choices.create(choice: "yes", is_correct: false)
choiceC = question.choices.create(choice: "Mabye", is_correct: false)
choiceD = question.choices.create(choice: "None of the Above", is_correct: true)
quiz = Quiz.create(name: "What is a SAN Quiz?")
question = quiz.questions.create(question: "SANs are typically deployed through what kind of switch?")
choiceA = question.choices.create(choice: "Director switch", is_correct: false)
choiceB = question.choices.create(choice: "Intelligent switch", is_correct: false)
choiceC = question.choices.create(choice: "IP switch", is_correct: true)
question = quiz.questions.create(question: "What is SAN?")
choiceA = question.choices.create(choice: "his is a general term for several approaches to using the Internet Prototol (IP) in a SAN usually over Gigabit Ethernet.", is_correct: false)
choiceB = question.choices.create(choice: "Bigger than an intelligent switch", is_correct: false)
choiceC = question.choices.create(choice: "Not an IP switch", is_correct: true)
quiz = Quiz.create(name: "Plant Quiz")
question = quiz.questions.create(question: "Which of the following best describes the term 'angiosperm'?")
choiceA = question.choices.create(choice: "Stored food in a seed", is_correct: false)
choiceB = question.choices.create(choice: "A plant", is_correct: false)
choiceC = question.choices.create(choice: "Flower plant", is_correct: true)
choiceD = question.choices.create(choice: "Pollen", is_correct: false)
question = quiz.questions.create(question: "The leaf-like structure that protects the budding flower is called the:")
choiceA = question.choices.create(choice: "Petal", is_correct: false)
choiceB = question.choices.create(choice: "Sepal", is_correct: true)
choiceC = question.choices.create(choice: "Anther", is_correct: false)
choiceD = question.choices.create(choice: "Stamen", is_correct: false)
quiz = Quiz.create(name: "Super Bowl Quiz")
question = quiz.questions.create(question: "Who won Super Bowl XVI?")
choiceA = question.choices.create(choice: "The Bengals", is_correct: false)
choiceB = question.choices.create(choice: "The 49ers", is_correct: false)
choiceC = question.choices.create(choice: "The St. Louis Seahawks", is_correct: false)
choiceD = question.choices.create(choice: "Bubbles The Whale", is_correct: true)
question = quiz.questions.create(question: "Who won Super Bowl XVIIRX?")
choiceA = question.choices.create(choice: "The Cowboys", is_correct: false)
choiceB = question.choices.create(choice: "The Eagles", is_correct: false)
choiceC = question.choices.create(choice: "French Fries and Ketchup", is_correct: false)
choiceD = question.choices.create(choice: "The Rolling Stone", is_correct: true)


